daftar_bea/urls.py
from django.conf.urls import url
from .views import index, list_bea, tambah_paket, daftar_paket_baru, post_paket_baru, post_tambah_paket

app_name = 'daftar-bea'

#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^daftar-paket/', daftar_paket_baru, name='daftar-paket'),
    url(r'^tambah-paket/', tambah_paket, name='tambah-paket'),
    url(r'^post-paket-baru/', post_paket_baru, name='post-paket-baru'),
    url(r'^post-tambah-paket/', post_tambah_paket, name='post-tambah-paket'),
    url(r'^list-bea/', list_bea, name='list-bea'),
]

login/urls.py
from django.conf.urls import url
from .views import index, login, logout


#url for app
app_name = 'login'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login', login, name='login'),
    url(r'^logout', logout, name='logout'),
]

simbion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import daftar_bea.urls as daftar_bea
import login.urls as login
import regis.urls as regis

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^daftar-bea/', include(daftar_bea, namespace='daftar-bea')),
    url(r'^login/', include(login, namespace='login')),
    url(r'^regis/', include(regis, namespace='regis')),
	url(r'^$', RedirectView.as_view(url='/login/', permanent='true')),
]

daftar_bea/models.py
from django.db import models

# Create your models here.

class Skema_beasiswa(models.Model):
    kode = models.IntegerField(primary_key=True)
    nama = models.CharField(max_length=50)
    jenis = models.CharField(max_length=20)
    deskripsi = models.CharField(max_length=50)
    nomor_identitas_donatur = models.CharField(max_length=20)

    class Meta:
        db_table = 'simbion.skema_beasiswa'

class Syarat_beasiswa(models.Model):
    kode_beasiswa = models.IntegerField(primary_key=True)
    syarat = models.CharField(max_length=50, primary_key=True)

    class Meta:
        db_table = 'simbion.syarat_beasiswa'

class Skema_beasiswa_aktif(models.Model):
    kode_skema_beasiswa = models.IntegerField(primary_key=True)
    no_urut = models.IntegerField(primary_key=True)
    tgl_mulai_pendaftaran = models.DateField()
    tgl_tutup_pendaftaran = models.DateField()
    periode_penerimaan = models.CharField(max_length=50)
    status = models.CharField(max_length=20)
    jumlah_pendaftar = models.IntegerField()

    class Meta:
        db_table = 'simbion.skema_beasiswa_aktif'

daftar_bea/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from .models import Skema_beasiswa_aktif, Skema_beasiswa, Syarat_beasiswa

# Create your views here.

dummy_donatur = '3543887734'

def index(request):
    response = {}
    return render(request, 'bea_main.html', response)

def daftar_paket_baru(request):
    response = {}
    return render(request, 'daftar_bea.html', response)

def tambah_paket(request):
    response = {}
    return render(request, 'tambah_bea.html', response)

def list_bea(request):
    response = {}
    response['skema_aktif'] = Skema_beasiswa_aktif.objects.raw("SELECT * FROM simbion.skema_beasiswa_aktif;")
    return render(request, 'list_bea.html', response)

@csrf_exempt
def post_paket_baru(request):
    try:
        if request.method == 'POST':
            with connection.cursor() as c:
                c.execute(create_insert_sql(table_name=Skema_beasiswa._meta.db_table, kode=request.POST['kode_paket'],
                                            nama=request.POST['nama_paket'], jenis=request.POST['jenis_paket'],
                                            deskripsi=request.POST['deskripsi'], nomor_identitas_donatur=dummy_donatur))

                c.execute(create_insert_sql(table_name=Syarat_beasiswa._meta.db_table,
                                            kode_beasiswa=request.POST['kode_paket'],
                                            syarat=request.POST['syarat']))
            messages.success(request, 'Paket baru anda telah terdaftar dalam sistem')
    except:
        messages.error(request, 'Tolong isi semua data dengan benar')
        return HttpResponseRedirect('/daftar-bea/daftar-paket')

    return HttpResponseRedirect('/daftar-bea/')

@csrf_exempt
def post_tambah_paket(request):
    try:
        if request.method == 'POST':
            with connection.cursor() as c:
                c.execute(create_insert_sql(table_name=Skema_beasiswa_aktif._meta.db_table,kode_skema_beasiswa=request.POST['kode_paket'],
                      no_urut=request.POST['no_urut'],tgl_mulai_pendaftaran=request.POST['tgl_buka'],
                      tgl_tutup_pendaftaran=request.POST['tgl_tutup'],status='Buka',
                                            periode_penerimaan='2017/2018'))

            messages.success(request, 'Beasiswa baru anda telah terdaftar dalam sistem')

    except:
        messages.error(request, 'Tolong isi semua data dengan benar')
        return HttpResponseRedirect('/daftar-bea/tambah-paket')

    return HttpResponseRedirect('/daftar-bea/')



def create_insert_sql(table_name, **fields):
    sql = 'INSERT INTO %s (' % table_name
    for field in fields:
        sql += '%s, ' % field
    sql = sql[:-2] + ') VALUES (' # Remove trailing comma
    for field in fields:
        sql += '\'%s\', ' % fields[field]
    sql = sql[:-2] + ');'
    return sql




daftar_bea/templates/bea_main.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link href="{% static 'img/favicon.png' %}" rel="shortcut icon"/>
        <meta charset="utf-8"/>
        <meta content="width=1920px, maximum-scale=1.0" name="viewport"/>
        <link href="{% static 'css/pilihanDonatur.css' %}" rel="stylesheet" type="text/css"/>
        <meta content="Launchpad by Anima" name="author">
        </meta>
    </head>
    <body style="margin: 0;
 background: rgba(255, 255, 255, 1.0);">
        <input id="anPageName" name="page" type="hidden" value="pilihandonatur"/>
        <div class="pilihan-donatur">
            <div style="width: 1920px; height: 100%; position:relative; margin:auto;">
                <img anima-src="{% static 'img/terimatolak beasiswarectangle 18.png' %}" class="rectangle18" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="/>
                <a href="{% url 'daftar-bea:daftar-paket' %}">
                    <div class="right-side">
                        {% for message in messages %}

                            <div class="alert alert-success">
                                <a class="close" href="#" data-dismiss="alert">×</a>

                                {{ message }}

                            </div>
                        {% endfor %}
                        <div class="form">
                            <div class="rectangle7">
                                <div class="mask">
                                </div>
                                <div class="paket-beasiswa-baru">
                                    Paket Beasiswa Baru
                                </div>
                                <div class="donatur-dapat-membua">
                                    Donatur dapat membuat
                                    <br/>
                                    paket baru disini.
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
                <a href="{% url 'daftar-bea:tambah-paket' %}">
                    <div class="right-side1">
                        <div class="form1">
                            <div class="rectangle71">
                                <div class="mask1">
                                </div>
                                <div class="tambah-beasiswa-dari">
                                    Tambah Beasiswa
                                    <br/>
                                    dari Paket
                                </div>
                                <div class="donatur-dapat-mengub">
                                    Donatur dapat mengubah
                                    <br/>
                                    paket beasiswa yang ada
                                    <br/>
                                    disini.
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
                <div class="beberapa-pilihan-unt">
                    Beberapa pilihan untuk anda.
                </div>
                <img anima-src="{% static 'img/pilihan donaturbaruback.png' %}" class="back" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="/>
            </div>
        </div>
        <!-- Scripts -->
        <script>
            anima_isHidden = function(e) {
                if (!(e instanceof HTMLElement)) return !1;
                if (getComputedStyle(e).display == "none") return !0; else if (e.parentNode && anima_isHidden(e.parentNode)) return !0;
                return !1;
            };
            anima_loadAsyncSrcForTag = function(tag) {
                var elements = document.getElementsByTagName(tag);
                var toLoad = [];
                for (var i = 0; i < elements.length; i++) {
                    var e = elements[i];
                    var src = e.getAttribute("src");
                    var loaded = (src != undefined && src.length > 0 && src != 'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==');
                    if (loaded) continue;
                    var asyncSrc = e.getAttribute("anima-src");
                    if (asyncSrc == undefined || asyncSrc.length == 0) continue;
                    if (anima_isHidden(e)) continue;
                    toLoad.push(e);
                }
                toLoad.sort(function(a, b) {
                    return anima_getTop(a) - anima_getTop(b);
                });
                for (var i = 0; i < toLoad.length; i++) {
                    var e = toLoad[i];
                    var asyncSrc = e.getAttribute("anima-src");
                    e.setAttribute("src", asyncSrc);
                }
            };
            anima_pauseHiddenVideos = function(tag) {
                var elements = document.getElementsByTagName("video");
                for (var i = 0; i < elements.length; i++) {
                    var e = elements[i];
                    var isPlaying = !!(e.currentTime > 0 && !e.paused && !e.ended && e.readyState > 2);
                    var isHidden = anima_isHidden(e);
                    if (!isPlaying && !isHidden && e.getAttribute("autoplay") == "autoplay") {
                        e.play();
                    } else if (isPlaying && isHidden) {
                        e.pause();
                    }
                }
            };
            anima_loadAsyncSrc = function(tag) {
                anima_loadAsyncSrcForTag("img");
                anima_loadAsyncSrcForTag("iframe");
                anima_loadAsyncSrcForTag("video");
                anima_pauseHiddenVideos();
            };
            var anima_getTop = function(e) {
                var top = 0;
                do {
                    top += e.offsetTop || 0;
                    e = e.offsetParent;
                } while (e);
                return top;
            };
            anima_loadAsyncSrc();
            anima_old_onResize = window.onresize;
            anima_new_onResize = undefined;
            anima_updateOnResize = function() {
                if (anima_new_onResize == undefined || window.onresize != anima_new_onResize) {
                    anima_new_onResize = function(x) {
                        if (anima_old_onResize != undefined) anima_old_onResize(x);
                        anima_loadAsyncSrc();
                    };
                    window.onresize = anima_new_onResize;
                    setTimeout(function() {
                        anima_updateOnResize();
                    }, 3000);
                }
            };
            anima_updateOnResize();
            setTimeout(function() {
                anima_loadAsyncSrc();
            }, 200);
        </script>
        <!-- End of Scripts -->
    </body>
</html>

daftar_bea/templates/daftar_bea.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link href="{% static 'img/favicon.png' %}" rel="shortcut icon"/>
        <meta charset="utf-8"/>
        <meta content="width=1920px, maximum-scale=1.0" name="viewport"/>
        <link href="{% static 'css/pilihanDonaturbaru.css' %}" rel="stylesheet" type="text/css"/>
        <meta content="Launchpad by Anima" name="author">
        </meta>
    </head>
    <body style="margin: 0;
 background: rgba(255, 255, 255, 1.0);">
        <input id="anPageName" name="page" type="hidden" value="pilihandonaturbaru"/>
        <div class="pilihan-donaturbaru">
            <div style="width: 1920px; height: 100%; position:relative; margin:auto;">
                <img anima-src="{% static 'img/terimatolak beasiswarectangle 18.png' %}" class="rectangle18" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="/>
                <div class="right-side">
                    {% for message in messages %}

                            <div class="alert alert-danger">
                                <a class="close" href="#" data-dismiss="alert">×</a>

                                {{ message }}

                            </div>
                    {% endfor %}
                    <div class="form">
                        <div class="rectangle7">
                            <div class="mask">

                                <form method="post" action="{% url 'daftar-bea:post-paket-baru' %}">
                                    {% csrf_token %}
                                    <div class="form-standard">
                                        <div class="form1">
                                            <input type="text" name="jenis_paket" class="inputdata">
                                        </div>
                                        <div class="label">
                                            Jenis Paket Beasiswa
                                        </div>
                                    </div>
                                    <div class="form-standard1">
                                        <div class="form2">
                                            <input type="text" name="nama_paket" class="inputdata">
                                        </div>
                                        <div class="optional1">
                                        </div>
                                        <div class="label1">
                                            Nama Paket Beasiswa
                                        </div>
                                    </div>
                                    <div class="form-standard2">
                                        <div class="form3">
                                            <input type="text" name="kode_paket" class="inputdata">
                                        </div>
                                        <div class="label2">
                                            Kode
                                        </div>
                                    </div>
                                    <div class="form-standard3">
                                        <div class="form4">
                                            <input type="text" name="deskripsi" class="inputdata">
                                        </div>
                                        <div class="label3">
                                            Deskripsi
                                        </div>
                                    </div>
                                    <div class="form-standard4">
                                        <div class="form5">
                                            <input type="text" name="syarat" class="inputdata">
                                        </div>
                                        <div class="label4">
                                            Syarat Beasiswa
                                        </div>
                                    </div>
                                    <button type="submit" class="mask1" value="submit">
                                    Submit
                                    </button>
                                </form>
                            </div>

                        </div>
                        <div class="form-pendaftaran-pak">
                            Form pendaftaran paket beasiswa:
                        </div>
                    </div>
                </div>
                <div class="isi-data-berikut">
                    Isi data berikut:
                </div>
                <img anima-src="{% static 'img/pilihan donaturbaruback.png' %}" class="back" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="/>
            </div>
        </div>
        <!-- Scripts -->
        <script>
            anima_isHidden = function(e) {
                if (!(e instanceof HTMLElement)) return !1;
                if (getComputedStyle(e).display == "none") return !0; else if (e.parentNode && anima_isHidden(e.parentNode)) return !0;
                return !1;
            };
            anima_loadAsyncSrcForTag = function(tag) {
                var elements = document.getElementsByTagName(tag);
                var toLoad = [];
                for (var i = 0; i < elements.length; i++) {
                    var e = elements[i];
                    var src = e.getAttribute("src");
                    var loaded = (src != undefined && src.length > 0 && src != 'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==');
                    if (loaded) continue;
                    var asyncSrc = e.getAttribute("anima-src");
                    if (asyncSrc == undefined || asyncSrc.length == 0) continue;
                    if (anima_isHidden(e)) continue;
                    toLoad.push(e);
                }
                toLoad.sort(function(a, b) {
                    return anima_getTop(a) - anima_getTop(b);
                });
                for (var i = 0; i < toLoad.length; i++) {
                    var e = toLoad[i];
                    var asyncSrc = e.getAttribute("anima-src");
                    e.setAttribute("src", asyncSrc);
                }
            };
            anima_pauseHiddenVideos = function(tag) {
                var elements = document.getElementsByTagName("video");
                for (var i = 0; i < elements.length; i++) {
                    var e = elements[i];
                    var isPlaying = !!(e.currentTime > 0 && !e.paused && !e.ended && e.readyState > 2);
                    var isHidden = anima_isHidden(e);
                    if (!isPlaying && !isHidden && e.getAttribute("autoplay") == "autoplay") {
                        e.play();
                    } else if (isPlaying && isHidden) {
                        e.pause();
                    }
                }
            };
            anima_loadAsyncSrc = function(tag) {
                anima_loadAsyncSrcForTag("img");
                anima_loadAsyncSrcForTag("iframe");
                anima_loadAsyncSrcForTag("video");
                anima_pauseHiddenVideos();
            };
            var anima_getTop = function(e) {
                var top = 0;
                do {
                    top += e.offsetTop || 0;
                    e = e.offsetParent;
                } while (e);
                return top;
            };
            anima_loadAsyncSrc();
            anima_old_onResize = window.onresize;
            anima_new_onResize = undefined;
            anima_updateOnResize = function() {
                if (anima_new_onResize == undefined || window.onresize != anima_new_onResize) {
                    anima_new_onResize = function(x) {
                        if (anima_old_onResize != undefined) anima_old_onResize(x);
                        anima_loadAsyncSrc();
                    };
                    window.onresize = anima_new_onResize;
                    setTimeout(function() {
                        anima_updateOnResize();
                    }, 3000);
                }
            };
            anima_updateOnResize();
            setTimeout(function() {
                anima_loadAsyncSrc();
            }, 200);
        </script>
        <!-- End of Scripts -->
    </body>
</html>

daftar_bea/templates/tambah_bea.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        <link href="{% static 'img/favicon.png' %}" rel="shortcut icon"/>
        <meta charset="utf-8"/>
        <meta content="width=1920px, maximum-scale=1.0" name="viewport"/>
        <link href="{% static 'css/pilihanDonaturbaru.css' %}" rel="stylesheet" type="text/css"/>
        <meta content="Launchpad by Anima" name="author">
        </meta>
    </head>
    <body style="margin: 0;
 background: rgba(255, 255, 255, 1.0);">
        <input id="anPageName" name="page" type="hidden" value="pilihandonaturbaru"/>
        <div class="pilihan-donaturbaru">
            <div style="width: 1920px; height: 100%; position:relative; margin:auto;">
                <img anima-src="{% static 'img/terimatolak beasiswarectangle 18.png' %}" class="rectangle18" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="/>
                <div class="right-side">
                    {% for message in messages %}

                        <div class="alert alert-danger">
                            <a class="close" href="#" data-dismiss="alert">×</a>

                            {{ message }}

                        </div>
                        {% endfor %}
                    <div class="form">
                        <div class="rectangle7">
                            <div class="mask">

                                <form method="post" action="{% url 'daftar-bea:post-tambah-paket' %}">
                                    {% csrf_token %}
                                    <div class="form-standard">
                                        <div class="form1">
                                            <input type="date" name="tgl_buka" class="inputdata">
                                        </div>
                                        <div class="label">
                                            Tanggal Mulai Pendaftaran
                                        </div>
                                    </div>
                                    <div class="form-standard1">
                                        <div class="form2">
                                            <input type="number" name="no_urut" class="inputdata">
                                        </div>
                                        <div class="optional1">
                                        </div>
                                        <div class="label1">
                                            Nomor Urut
                                        </div>
                                    </div>
                                    <div class="form-standard2">
                                        <div class="form3">
                                            <input type="text" name="kode_paket" class="inputdata">
                                        </div>
                                        <div class="label2">
                                            Kode Beasiswa
                                        </div>
                                    </div>
                                    <div class="form-standard3">
                                        <div class="form4">
                                            <input type="date" name="tgl_tutup" class="inputdata">
                                        </div>
                                        <div class="label3">
                                            Tanggal Tutup Pendaftaran
                                        </div>
                                    </div>
                                    <button type="submit" class="mask1" value="Submit">
                                    Submit
                                    </button>
                                </form>
                            </div>

                        </div>
                        <div class="form-pendaftaran-pak">
                            Form pendaftaran paket beasiswa:
                        </div>
                    </div>
                </div>
                <div class="isi-data-berikut">
                    Isi data berikut:
                </div>
                <img anima-src="{% static 'img/pilihan donaturbaruback.png' %}" class="back" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw=="/>
            </div>
        </div>
        <!-- Scripts -->
        <script>
            anima_isHidden = function(e) {
                if (!(e instanceof HTMLElement)) return !1;
                if (getComputedStyle(e).display == "none") return !0; else if (e.parentNode && anima_isHidden(e.parentNode)) return !0;
                return !1;
            };
            anima_loadAsyncSrcForTag = function(tag) {
                var elements = document.getElementsByTagName(tag);
                var toLoad = [];
                for (var i = 0; i < elements.length; i++) {
                    var e = elements[i];
                    var src = e.getAttribute("src");
                    var loaded = (src != undefined && src.length > 0 && src != 'data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACH5BAEAAAAALAAAAAABAAEAAAICRAEAOw==');
                    if (loaded) continue;
                    var asyncSrc = e.getAttribute("anima-src");
                    if (asyncSrc == undefined || asyncSrc.length == 0) continue;
                    if (anima_isHidden(e)) continue;
                    toLoad.push(e);
                }
                toLoad.sort(function(a, b) {
                    return anima_getTop(a) - anima_getTop(b);
                });
                for (var i = 0; i < toLoad.length; i++) {
                    var e = toLoad[i];
                    var asyncSrc = e.getAttribute("anima-src");
                    e.setAttribute("src", asyncSrc);
                }
            };
            anima_pauseHiddenVideos = function(tag) {
                var elements = document.getElementsByTagName("video");
                for (var i = 0; i < elements.length; i++) {
                    var e = elements[i];
                    var isPlaying = !!(e.currentTime > 0 && !e.paused && !e.ended && e.readyState > 2);
                    var isHidden = anima_isHidden(e);
                    if (!isPlaying && !isHidden && e.getAttribute("autoplay") == "autoplay") {
                        e.play();
                    } else if (isPlaying && isHidden) {
                        e.pause();
                    }
                }
            };
            anima_loadAsyncSrc = function(tag) {
                anima_loadAsyncSrcForTag("img");
                anima_loadAsyncSrcForTag("iframe");
                anima_loadAsyncSrcForTag("video");
                anima_pauseHiddenVideos();
            };
            var anima_getTop = function(e) {
                var top = 0;
                do {
                    top += e.offsetTop || 0;
                    e = e.offsetParent;
                } while (e);
                return top;
            };
            anima_loadAsyncSrc();
            anima_old_onResize = window.onresize;
            anima_new_onResize = undefined;
            anima_updateOnResize = function() {
                if (anima_new_onResize == undefined || window.onresize != anima_new_onResize) {
                    anima_new_onResize = function(x) {
                        if (anima_old_onResize != undefined) anima_old_onResize(x);
                        anima_loadAsyncSrc();
                    };
                    window.onresize = anima_new_onResize;
                    setTimeout(function() {
                        anima_updateOnResize();
                    }, 3000);
                }
            };
            anima_updateOnResize();
            setTimeout(function() {
                anima_loadAsyncSrc();
            }, 200);
        </script>
        <!-- End of Scripts -->
    </body>
</html>