login/urls.py
from django.conf.urls import url
from .views import index, login, logout


#url for app
app_name = 'login'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^login', login, name='login'),
    url(r'^logout', logout, name='logout'),
]

regis/urls.py
from django.conf.urls import url
from .views import index, donatur_yayasan, donatur_individual, regis_mahasiswa, role_donatur


#url for app
app_name = 'regis'
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^donatur-yayasan', donatur_yayasan, name='donatur_yayasan'),
    url(r'^donatur-individual', donatur_individual, name='donatur_individual'),
    url(r'^mahasiswa',regis_mahasiswa, name='regis_mahasiswa'),
    url(r'^role-donatur',role_donatur, name='role_donatur'),
]

simbion/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import daftar_bea.urls as daftar_bea
import login.urls as login
import regis.urls as regis

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^daftar-bea/', include(daftar_bea, namespace='daftar-bea')),
    url(r'^login/', include(login, namespace='login')),
    url(r'^regis/', include(regis, namespace='regis')),
	url(r'^$', RedirectView.as_view(url='/login/', permanent='true')),
]

regis/models.py
from django.db import models


class pengguna(models.Model):
    username = models.CharField(max_length=20 , primary_key=True)
    password = models.CharField(max_length=20)
    role = models.CharField(max_length=20)
    class Meta:
        db_table = 'simbion.pengguna'

class donatur(models.Model):
    nomor_identitas = models.CharField(max_length=20, primary_key=True)
    email = models.CharField(max_length=50)
    nama = models.CharField(max_length=20)
    npwp = models.CharField(max_length=20)
    no_telp = models.CharField(max_length=20)
    alamat = models.CharField(max_length=50)
    username = models.ForeignKey(pengguna ,on_delete= models.CASCADE, db_column='username')
    
    class Meta:
        db_table = 'simbion.donatur'

class admin(models.Model):
    username = models.ForeignKey(pengguna,on_delete= models.CASCADE, db_column='username')
    class Meta:
        db_table = 'simbion.admin'

class individual_donor(models.Model):
    nik = models.CharField(max_length=16)
    nomor_identitas_donatur = models.ForeignKey(donatur ,on_delete= models.CASCADE, db_column='nomor_identitas_donatur')
    class Meta:
        db_table = 'simbion.individual_donor'


class yayasan(models.Model):
    no_sk_yayasan = models.CharField(max_length=20)
    email = models.CharField(max_length=50)
    nama = models.CharField(max_length=50)
    no_telp_cp = models.CharField(max_length=20)
    nomor_identitas_donatur = models.ForeignKey(donatur ,on_delete= models.CASCADE,db_column='nomor_identitas_donatur')
    class Meta:
        db_table = 'simbion.yayasan'



class mahasiswa(models.Model) :
    npm = models.CharField(max_length=20 , primary_key=True)
    email = models.CharField(max_length=50)
    nama = models.CharField(max_length=50)
    no_telp = models.CharField(max_length=20)
    alamat_tinggal = models.CharField(max_length=50)
    alamat_domisili = models.CharField(max_length=50)
    nama_bank = models.CharField(max_length=50)
    no_rekening = models.CharField(max_length=20)
    nama_pemilik = models.CharField(max_length=20)
    username = models.ForeignKey(pengguna ,on_delete= models.CASCADE, db_column='username')
    class Meta:
        db_table = 'simbion.mahasiswa'

# Create your models here.

regis/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from django.db import connection
from .models import pengguna, mahasiswa, donatur, individual_donor, yayasan
import os
import json
response = {}

def index (request):
    html = 'regis/pilihanroleanda.html'
    return render(request, html, response)

def donatur_yayasan (request):
    return render (request, 'regis/donatur_yayasan.html', response)

def donatur_individual (request):
    return render (request, 'regis/donatur_individual.html', response)

def regis_mahasiswa (request):
    return render (request, 'regis/mahasiswa.html', response)

def role_donatur (request):
    return render (request, 'regis/pilihroledonatur.html', response)

def sign_mahasiswa (request):
    if request.method == 'POST':
        cursor = connection.cursor()

        username = request.POST['username']
        password = request.POST['password']
        npm = request.POST['npm']
        email = request.POST['email']
        nama = request.POST['nama']
        no_telp = request.POST['no_telp']
        alamat_tinggal = request.POST['alamat_tinggal']
        alamat_domisili = request.POST['alamat_domisili']
        nama_bank = request.POST['nama_bank']
        no_rekening = request.POST['no_rekening']
        nama_pemilik = request.POST['nama_pemilik']

        cursor.execute('SELECT username FROM pengguna;')
        daftarPengguna =  cursor.fetchall()
        cursor.execute('SELECT npm FROM mahasiswa;')
        daftarMahasiswa = cursor.fetchall()

        f_username = False
        f_npm = False

        for uname in daftarPengguna :
            if (uname[0] == username):
                f_username = True
        for nomor in daftarMahasiswa :
            if (nomor[0] == npm):
                f_npm = True

        for huruf in password :
            if (huruf.isdigit()):
                f_angka = True
        if len(password)>7 :
            f_panjang = True

        f_password = f_panjang and f_angka


        if (not f_username) and f_password and (not f_npm) :
            
            query = "INSERT INTO pengguna VALUES ('%s', '%s', 'mahasiswa');" %\
            (username, password)
            cursor.execute(query)
            query2 = "INSERT INTO mahasiswa VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s');" %\
            (npm, email, nama, no_telp, alamat_tinggal, alamat_domisili, nama_bank, no_rekening, nama_pemilik, username)
            cursor.execute(query2)
        
        cursor.close()

        return HttpResponseRedirect(reverse('login:index'))

def sign_individual(request) :
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        nomor_identitas = request.POST['nomor_identitas']
        nik = request.POST['nik']
        email = request.POST['email']
        nama = request.POST['nama']
        npwp = request.POST['npwp']
        no_telp = request.POST['no_telp']
        alamat = request.POST['alamat']

        cursor = connection.cursor()

        cursor.execute('SELECT username FROM pengguna;')
        daftarPengguna = cursor.fetchall()

        f_username = False

        for uname in daftarPengguna :
            if (uname[0] == username):
                f_username = True

        cursor.execute('SELECT nomor_identitas FROM donatur;')
        daftarNomorIdentitas = cursor.fetchall()
        f_nomor_identitas = False

        for nomor in daftarNomorIdentitas :
            if (nomor[0] == nomor_identitas):
                f_nomor_identitas = True

    
        f_angka = False
        f_panjang = False

        for huruf in password :
            if (huruf.isdigit()):
                f_angka = True
        if len(password)>7 :
            f_panjang = True

        f_password = f_panjang and f_angka

        daftarNIK = cursor.fetchall()
        
        for nomor in daftarNIK :
            if (nomor[0] == nik):
                f_nik = True
            if len(nik)==16:
                f_nik_panjang = True

        cursor.execute('SELECT nik FROM individual_donor;')

        if (not f_username) and f_password and (not f_nomor_identitas) and (not f_nik) and f_nik_panjang :
            query = "INSERT INTO pengguna VALUES ('%s', '%s', 'donatur');" %\
            (username, password)
            cursor.execute(query)
            query2 = "INSERT INTO donatur VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s');" %\
            (nomor_identitas, email, nama, npwp, no_telp, alamat, username)
            query3 = "INSERT INTO individual_donor VALUES ('%s', '%s');" %\
            (nik, nomor_identitas)
            cursor.execute(query2)
            cursor.execute(query3)
            cursor.close()

@csrf_exempt
def sign_yayasan (request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        nomor_identitas = request.POST['nomor_identitas']
        nomor_sk_yayasan = request.POST['nomor_sk_yayasan']
        email = request.POST['email']
        nama = request.POST['nama']
        no_telp = request.POST['no_telp']
        npwp = request.POST['npwp']
        alamat = request.POST['alamat']

        cursor = connection.cursor()
        cursor.execute('SELECT username FROM pengguna')
        daftarPengguna = cursor.fetchall()

        f_username = False

        for uname in daftarPengguna :
            if (uname[0] == username):
                f_username = True

        cursor.execute('SELECT nomor_identitas FROM donatur')
        daftarNomorIdentitas = cursor.fetchall()
        f_nomor_identitas = False

        for nomor in daftarNomorIdentitas :
            if (nomor[0] == nomor_identitas):
                f_nomor_identitas = True

        f_angka = False
        f_panjang = False

        for huruf in password :
            if (huruf.isdigit()):
                f_angka = True
        if len(password)>7 :
            f_panjang = True

        f_password = f_panjang and f_angka

        cursor.execute('SELECT no_sk_yayasan FROM yayasan;')
        daftar_nomor_SK_yayasan = cursor.fetchall()


        for nomor in daftar_nomor_SK_yayasan :
            if (nomor[0] == daftar_nomor_SK_yayasan):
                f_SK = True

        if (not f_username) and f_password and (not f_nomor_identitas) and (not f_SK) :
            query = "INSERT INTO pengguna VALUES ('%s', '%s', 'donatur');" %\
            (username, password)
            cursor.execute(query)
            query2 = "INSERT INTO donatur VALUES ('%s', '%s', '%s', '%s', '%s', '%s', '%s');" %\
            (nomor_identitas, email, nama, npwp, no_telp, alamat, username)
            query3 = "INSERT INTO yayasan VALUES ('%s', '%s', '%s', '%s', '%s');" %\
            (nomor_sk_yayasan, email, nama, no_telp, nomor_identitas)
            cursor.execute(query2)
            cursor.execute(query3)
            cursor.close()

        return HttpResponseRedirect(reverse('login:index'))


regis/templates/regis/donatur_individual.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mahaiswa</title>
</head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h1 style="text-align: center">Registrasi Donatur Individual</h1>
    <form action="{% url 'regis:sign_individual' %}" method="POST">
        {% csrf_token %}
        <p>
                <label for="username"> Username </label>
                <input class="form-control" type="text" id="username" name="username" required>
        </p>
        <p>
            <label for="password"> Your password </label>
            <input type="password" id="password" name="password" required>
        </p>
        <p>
                <label for="npm"> Nomor Identitas :</label>
                <input class="form-control" type="text" id="npm" name="npm" required>
        </p>
        <p>
                <label for="email"> NIK :</label>
                <input class="form-control" type="email" id="email" name="email" required>
        </p>
        <p>
                <label for="nama"> Email : </label>
                <input class="form-control" type="text" id="nama" name="nama" required>
        </p>
        <p>
                <label for="no_telp"> Nama Lengkap : </label>
                <input class="form-control" type="text" id="no_telp" name="no_telp">
        </p>
        <p>
                <label for="alamat_tinggal"> NPWP : </label>
                <input class="form-control" type="text" id="alamat_tinggal" name="alamat_tinggal" required>
        </p>
        <p>
                <label for="alamat_domisili">Nomor Telpon: </label>
                <input class="form-control" type="text" id="alamat_domisili" name="alamat_domisili" required>
        </p>
        <p>
                <label for="nama_bank"> Alamat: </label>
                <input class="form-control" type="text" id="nama_bank" name="nama_bank" required>
                
        </p>
        <p>
                <label for="no_rekening"> Nomor Rekening : </label>
                <input class="form-control" type="text" id="no_rekening" name="no_rekening" required>
        </p>

        <input type="submit" class="btn btn-default">
        
    </form>
</body>

</html>



regis/templates/regis/donatur_yayasan.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mahaiswa</title>
</head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h1 style="text-align: center">Registrasi Donatur Yayasan</h1>
    <form action="{% url 'regis:sign_yayasan' %}" method="POST">
        {% csrf_token %}
        <p>
                <label for="username"> Username </label>
                <input class="form-control" type="text" id="username" name="username" required>
        </p>
        <p>
            <label for="password"> Your password </label>
            <input type="password" id="password" name="password" required>
        </p>
        <p>
                <label for="npm"> Nomor identitas :</label>
                <input class="form-control" type="text" id="npm" name="npm" required>
        </p>
        <p>
                <label for="email"> SK yayasan :</label>
                <input class="form-control" type="email" id="email" name="email" required>
        </p>
        <p>
                <label for="nama"> email : </label>
                <input class="form-control" type="text" id="nama" name="nama" required>
        </p>
        <p>
                <label for="no_telp"> Nama yayasan : </label>
                <input class="form-control" type="text" id="no_telp" name="no_telp">
        </p>
        <p>
                <label for="alamat_tinggal"> nomor CP : </label>
                <input class="form-control" type="text" id="alamat_tinggal" name="alamat_tinggal" required>
        </p>
        <p>
                <label for="alamat_domisili"> NPWP : </label>
                <input class="form-control" type="text" id="alamat_domisili" name="alamat_domisili" required>
        </p>
        <p>
                <label for="nama_bank"> Alamat yayasan : </label>
                <input class="form-control" type="text" id="nama_bank" name="nama_bank" required>
                
        </p>
        <p>
                <label for="no_rekening"> Nomor Rekening : </label>
                <input class="form-control" type="text" id="no_rekening" name="no_rekening" required>
        </p>
        <p>
                <label for="nama_pemilik"> Nama Pemilik : </label>
                <input class="form-control" type="text" id="nama_pemilik" name="nama_pemilik" required>
        </p>

        <input type="submit" class="btn btn-default">
        
    </form>
</body>

</html>



regis/templates/regis/mahasiswa.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mahaiswa</title>
</head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua">
    <h1 style="text-align: center">Registrasi Mahasiswa</h1>
    <form action="{% url 'regis:sign_mahasiswa' %}" method="POST">
        {% csrf_token %}
        <p>
                <label for="username"> Username </label>
                <input class="form-control" type="text" id="username" name="username" required>
        </p>
        <p>
            <label for="password"> Your password </label>
            <input type="password" id="password" name="password" required>
        </p>
        <p>
                <label for="npm"> NPM :</label>
                <input class="form-control" type="text" id="npm" name="npm" required>
        </p>
        <p>
                <label for="email"> Email :</label>
                <input class="form-control" type="email" id="email" name="email" required>
        </p>
        <p>
                <label for="nama"> Nama Lengkap : </label>
                <input class="form-control" type="text" id="nama" name="nama" required>
        </p>
        <p>
                <label for="no_telp"> Nomor Telepon : </label>
                <input class="form-control" type="text" id="no_telp" name="no_telp">
        </p>
        <p>
                <label for="alamat_tinggal"> Alamat Tempat Tinggal : </label>
                <input class="form-control" type="text" id="alamat_tinggal" name="alamat_tinggal" required>
        </p>
        <p>
                <label for="alamat_domisili"> Alamat Domisili : </label>
                <input class="form-control" type="text" id="alamat_domisili" name="alamat_domisili" required>
        </p>
        <p>
                <label for="nama_bank"> Instansi Bank : </label>
                <input class="form-control" type="text" id="nama_bank" name="nama_bank" required>
                
        </p>
        <p>
                <label for="no_rekening"> Nomor Rekening : </label>
                <input class="form-control" type="text" id="no_rekening" name="no_rekening" required>
        </p>
        <p>
                <label for="nama_pemilik"> Nama Pemilik : </label>
                <input class="form-control" type="text" id="nama_pemilik" name="nama_pemilik" required>
        </p>

        <input type="submit" class="btn btn-default">
        
    </form>
</body>

</html>



regis/templates/regis/pilihanroleanda.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua" align= "center">
    <h1 style="text-align: center">pilih role anda</h1>
    <a href="{% url 'regis:role_donatur' %}">Donatur</a><br>
    <a href="{% url 'regis:regis_mahasiswa' %}">Mahasiswa</a><br>

</body>

</html>



regis/templates/regis/pilihroledonatur.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<body style="background-color: aqua" align= "center">
    <h1 style="text-align: center">pilih role anda</h1>
    <a href="{% url 'regis:donatur_individual' %}">Donatur Individual</a><br>
    <a href="{% url 'regis:donatur_yayasan' %}">Donatur Yayasan</a><br>

</body>

</html>

